パスワード入力用関数を追加

diff --git a/lib/assert b/lib/assert
--- a/lib/assert
+++ b/lib/assert
@@ -351,3 +351,28 @@ assert.select() {
   # return 選択された選択肢文言
   assert.choice -o "$@"
 }
+
+assert.password() {
+  # 指定した名前の変数に値を設定します
+  # ただし、表示の際には * で表示されます
+  # param1 変数名
+  local variable=${1}
+  local invisible=
+  [[ -z "${variable}" ]] && {
+    echo "variable-name is required!" >&2
+    return 1
+  }
+  echo -n "$variable: "
+  while IFS= read -r -n 1 -s key && [[ -n "$key" ]]; do
+    if [[ "$key" == $'\x7f' ]];then # backspace
+      tput cub 1
+      tput el
+      invisible="${invisible:0:${#invisible}-1}"
+    else
+      echo -n "*"
+      invisible+="$key"
+    fi
+  done
+  read -r -s $variable <<<"$invisible"
+  echo;
+}
