記述を簡略化

diff --git a/lib/sub b/lib/sub
--- a/lib/sub
+++ b/lib/sub
@@ -8,41 +8,38 @@ source "${base}/file"
 # ----------------
 #     関数定義
 # ----------------
-sub.new() {
+sub.new() (
   # 設定ファイルを読み込んでサブプロンプトを開始します
   # 設定ファイルは親フォルダを遡って探索されます
   # 設定ファイルが見つからない場合、カレントディレクトリにファイルを作成します
   # param1 設定ファイル名（デフォルト: .subrc）
   local initfile="${1:-.subrc}"
-  (
-    local ifile="$(file.isBelongedTo ${initfile})"
-    [[ "x${ifile}" == "x" ]] && {
-      ifile="$(pwd)/$(basename ${initfile})"
-      cat >${ifile} <<EOF
+  local ifile="$(file.isBelongedTo ${initfile})"
+  [[ "x${ifile}" == "x" ]] && {
+    ifile="$(pwd)/$(basename ${initfile})"
+    cat >${ifile} <<EOF
 #!/bin/bash --init-file
 PS1="\[\033[01;34m\]\u\[\033[00m\]\$ "
 [[ -d "${base}" ]] && for f in \$(find "${base}" -type f);do source "\${f}"; done
 EOF
-      echo "${initfile} is not found."
-      echo "created init-file: ${ifile}"
-    }
-    bash --init-file ${ifile}
-  )
-}
+    echo "${initfile} is not found."
+    echo "created init-file: ${ifile}"
+  }
+  bash --init-file ${ifile}
+)
 
-sub.temp() {
+sub.temp() (
   # 使い捨てのサブプロンプト環境を開始します
+  # param1 設定ファイル名（デフォルト: .subrc）
   local initfile="${1:-.subrc}"
   initfile="$(file.isBelongedTo ${initfile})"
-  (
-    unset tmpfile
-    trap '[[ "${tmpfile}" ]] && rm -f ${tmpfile}' EXIT HUP INT QUIT TERM RETURN
-    local tmpfile=$(mktemp 2>/dev/null||mktemp -t tmp)
-    cat >${tmpfile} <<EOF
+  unset tmpfile
+  trap '[[ "${tmpfile}" ]] && rm -f ${tmpfile}' EXIT HUP INT QUIT TERM RETURN
+  local tmpfile=$(mktemp 2>/dev/null||mktemp -t tmp)
+  cat >${tmpfile} <<EOF
 #!/bin/bash --init-file
 PS1="\[\033[01;34m\]\u\[\033[00m\]\$ "
 [[ -d "${base}" ]] && for f in \$(find "${base}" -type f);do source "\${f}"; done
 EOF
-    bash --init-file ${tmpfile}
-  )
-}
+  bash --init-file ${tmpfile}
+)
